%%{init: { "sequence": { "wrap": true, "wrapPadding": 10, "useMaxWidth": true } } }%%
sequenceDiagram
    autonumber
    box rgba(230,245,255,0.3) Client
        participant A
    end
    A->>A: hello
